# Generated by Django 5.0.6 on 2024-06-30 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("PERECIVEL", "Perecíveis"),
                            ("NAOPERECIVEL", "Não perecíveis"),
                        ],
                        max_length=30,
                        verbose_name="Categoria:",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=194, verbose_name="Nome do produto:"),
                ),
                (
                    "descricao",
                    models.TextField(
                        max_length=194, verbose_name="Descrição do produto:"
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto",
                "verbose_name_plural": "Produtos",
                "db_table": "produto",
            },
        ),
        migrations.CreateModel(
            name="ProdutoEstoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantidade",
                    models.IntegerField(verbose_name="Quantidade de produto:"),
                ),
                (
                    "data_de_validade",
                    models.DateField(verbose_name="Data de validade:"),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estoque",
                "verbose_name_plural": "Estoques",
                "db_table": "Estoque",
            },
        ),
    ]
