# Generated by Django 5.0.6 on 2024-06-30 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("estoque", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_de_transacao",
                    models.CharField(
                        choices=[("ENTRADA", "Entrada"), ("SAIDA", "Saída")],
                        max_length=30,
                        verbose_name="Tipo de transação:",
                    ),
                ),
                (
                    "data",
                    models.DateField(
                        auto_now_add=True, verbose_name="Data da transação"
                    ),
                ),
                (
                    "gerente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.gerente",
                    ),
                ),
                (
                    "vendedor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="usuarios.vendedor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transação",
                "verbose_name_plural": "Transações",
                "db_table": "transacao",
            },
        ),
        migrations.CreateModel(
            name="ProdutosTransacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "qtd_de_produtos",
                    models.FloatField(verbose_name="Quantidade de produto:"),
                ),
                (
                    "produto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="estoque.produto",
                    ),
                ),
                (
                    "transacao",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="transacao.transacao",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produto de Transação",
                "verbose_name_plural": "Produtos de transações",
                "db_table": "produtostransacao",
            },
        ),
    ]
